// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmoothVideoPlayer.Data;

#nullable disable

namespace SmoothVideoPlayer.Data.Migrations
{
    [DbContext(typeof(WordTranslationDbContext))]
    partial class WordTranslationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("SmoothVideoPlayer.Models.WordTranslationRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AudioPath")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateAdded")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateAddedToAnki")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("TEXT");

                    b.Property<string>("EngWord")
                        .HasColumnType("TEXT");

                    b.Property<string>("MoviePath")
                        .HasColumnType("TEXT");

                    b.Property<string>("ScreenshotPath")
                        .HasColumnType("TEXT");

                    b.Property<string>("SubEngKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("SubRuKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("SubtitleEngContext")
                        .HasColumnType("TEXT");

                    b.Property<string>("SubtitleRuContext")
                        .HasColumnType("TEXT");

                    b.Property<string>("SubtitlesEngPath")
                        .HasColumnType("TEXT");

                    b.Property<string>("SubtitlesRuPath")
                        .HasColumnType("TEXT");

                    b.Property<string>("WordRu")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("WordTranslationRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
